name: 'Aqua Login'
description: 'Log in to aqua cloud instance.'
branding:
  icon: 'droplet'
  color: 'blue'
inputs:
  aqua-base-url:
    description: 'Base url for aqua rest api'
    required: true
    default: 'https://aqua-saas2.andagon.com/aquaWebNG/api'
  aqua-username:
    description: 'username to use for login to aqua'
    required: true
  aqua-password:
    description: 'password to use for login to aqua'
    required: true
outputs:
  token:
    description: 'The bear token to communicated with aqua rest api.'
runs:
  using: 'node12'
  main: 'dist/index.js'
